//
//  AlarmType+AlecrimCoreDataAttributes.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData


// MARK: - AlarmType query attributes

extension AlarmType {

    static let name = AlecrimCoreData.Attribute<String>("name")

    static let alarms = AlecrimCoreData.Attribute<Set<Alarm>>("alarms")

}

// MARK: - AttributeProtocol extensions

extension AlecrimCoreData.AttributeProtocol where Self.ValueType: AlarmType {

    var name: AlecrimCoreData.Attribute<String> { return AlecrimCoreData.Attribute<String>("name", self) }

    var alarms: AlecrimCoreData.Attribute<Set<Alarm>> { return AlecrimCoreData.Attribute<Set<Alarm>>("alarms", self) }

}

// MARK: - NSManagedObjectContext extensions

extension NSManagedObjectContext {

    var alarmTypes: AlecrimCoreData.Table<AlarmType> { return AlecrimCoreData.Table<AlarmType>(context: self) }

}

