//
//  Alarm+AlecrimCoreDataAttributes.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData


// MARK: - Alarm query attributes

extension Alarm {

    static let date = AlecrimCoreData.Attribute<Date>("date")
    static let isActive = AlecrimCoreData.Attribute<Bool>("isActive")
    static let label = AlecrimCoreData.Attribute<String>("label")

    static let type = AlecrimCoreData.Attribute<AlarmType>("type")

}

// MARK: - AttributeProtocol extensions

extension AlecrimCoreData.AttributeProtocol where Self.ValueType: Alarm {

    var date: AlecrimCoreData.Attribute<Date> { return AlecrimCoreData.Attribute<Date>("date", self) }
    var isActive: AlecrimCoreData.Attribute<Bool> { return AlecrimCoreData.Attribute<Bool>("isActive", self) }
    var label: AlecrimCoreData.Attribute<String> { return AlecrimCoreData.Attribute<String>("label", self) }

    var type: AlecrimCoreData.Attribute<AlarmType> { return AlecrimCoreData.Attribute<AlarmType>("type", self) }

}

// MARK: - NSManagedObjectContext extensions

extension NSManagedObjectContext {

    var alarms: AlecrimCoreData.Table<Alarm> { return AlecrimCoreData.Table<Alarm>(context: self) }

}

