//
//  Alarm+CoreDataClass.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

@objc(Alarm)
final class Alarm: Entity {

}

