//
//  AlarmType+CoreDataProperties.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

// MARK: - AlarmType properties

extension AlarmType {

    @NSManaged var name: String

    @NSManaged var alarms: Set<Alarm>

}

// MARK: - AlarmType KVC compliant to-many accessors and helpers

extension AlarmType {

    @objc(addAlarmsObject:)
    @NSManaged func addToAlarms(_ value: Alarm)

    @objc(removeAlarmsObject:)
    @NSManaged func removeFromAlarms(_ value: Alarm)

    @objc(addAlarms:)
    @NSManaged func addToAlarms(_ values: Set<Alarm>)

    @objc(removeAlarms:)
    @NSManaged func removeFromAlarms(_ values: Set<Alarm>)

}

