//
//  Entity+AlecrimCoreDataAttributes.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData


// MARK: - Entity query attributes

extension Entity {

    static let identifier = AlecrimCoreData.Attribute<String>("identifier")

}

// MARK: - AttributeProtocol extensions

extension AlecrimCoreData.AttributeProtocol where Self.ValueType: Entity {

    var identifier: AlecrimCoreData.Attribute<String> { return AlecrimCoreData.Attribute<String>("identifier", self) }

}

// MARK: - NSManagedObjectContext extensions

extension NSManagedObjectContext {

    var entities: AlecrimCoreData.Table<Entity> { return AlecrimCoreData.Table<Entity>(context: self) }

}

