//
//  DataContext.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import AlecrimCoreData

let dataContext = DataContext()!

final class DataContext: AlecrimCoreData.Context {

    var events: AlecrimCoreData.Table<Event> { return AlecrimCoreData.Table<Event>(context: self) }
    var subEvents: AlecrimCoreData.Table<SubEvent> { return AlecrimCoreData.Table<SubEvent>(context: self) }

}
