//
//  Event.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

class Event: NSManagedObject {

    @NSManaged var timeStamp: NSDate

    @NSManaged var child: SubEvent?

    @NSManaged var children: Set<SubEvent>

}

// MARK: - AlecrimCoreData query attributes

extension Event {

    static let timeStamp = AlecrimCoreData.Attribute<NSDate>("timeStamp")

    static let child = SubEventAttribute<SubEvent?>("child")

    static let children = AlecrimCoreData.EntitySetAttribute<Set<SubEvent>>("children")

}

class EventAttribute<T>: AlecrimCoreData.SingleEntityAttribute<T> {

    override init(_ name: String) { super.init(name) }

    lazy var timeStamp: AlecrimCoreData.Attribute<NSDate> = { AlecrimCoreData.Attribute<NSDate>("\(self.___name).timeStamp") }()

    lazy var child: SubEventAttribute<SubEvent?> = { SubEventAttribute<SubEvent?>("\(self.___name).child") }()

    lazy var children: AlecrimCoreData.EntitySetAttribute<Set<SubEvent>> = { AlecrimCoreData.EntitySetAttribute<Set<SubEvent>>("\(self.___name).children") }()

}
