//
//  SubEvent.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

class SubEvent: NSManagedObject {

    @NSManaged var title: String?

}

// MARK: - AlecrimCoreData query attributes

extension SubEvent {

    static let title = AlecrimCoreData.Attribute<String?>("title")

}

class SubEventAttribute<T>: AlecrimCoreData.SingleEntityAttribute<T> {

    override init(_ name: String) { super.init(name) }

    lazy var title: AlecrimCoreData.Attribute<String?> = { AlecrimCoreData.Attribute<String?>("\(self.___name).title") }()

}
